@startuml
class Magician {
}
Character <|-- Magician
Magician --> "boxSize" Vector2
Magician --> "enemyLayer" LayerMask
Magician --> "playerLayer" LayerMask
Magician --> "targetLayer" LayerMask
@enduml
